<?php

$INSERT[] = "INSERT INTO categories (id, name, image) VALUES
(1, 'Apps', 'cat_apps.png'),
(2, 'Games', 'cat_games.png'),
(3, 'Movies', 'cat_movies.png'),
(4, 'Music', 'cat_music.png'),
(5, 'Episodes', 'cat_episodes.png'),
(6, 'XXX', 'cat_xxx.png'),
(7, 'Misc', 'cat_misc.png')";

$INSERT[] = "INSERT INTO config (mysql_host, mysql_db, mysql_user, mysql_pass, domain_url, announce_url, site_online, members_only, site_mail, site_name, image_dic, torrent_dic, peer_limit, max_members, signup_timeout, min_votes, autoclean_interval, announce_interval,max_torrent_size, max_dead_torrent_time, posts_read_expiry, max_login_attempts, dictbreaker, delete_old_torrents, dead_torrents, maxfilesize, attachment_dir, forum_width, maxsubjectlength, postsperpage, use_attachment_mod, use_poll_mod, forum_stats_mod, use_flood_mod, limmit, minutes) VALUES
('localhost', '???', '???', '???', 'http://www.yoursite.com', 'http://www.yoursite.com/announce.php', 'true', 'true', 'noreply@freetsp.com', 'FREETSP', '/images/', 'torrents', '50000', '7500', '86400*3', '1', '900', '60 * 30', '1000000', '3 * 3600', '14 * 86400', '6', 'functions/dictbreaker', '1', '28', '1024*1024', 'forum_attachments', '100%', '80', '25', 'true', 'true', 'true', 'true', '10', '5')";

$INSERT[] = "INSERT INTO countries (id, name, flagpic) VALUES
(1, 'Abkhazia', 'Abkhazia.png'),
(2, 'Afghanistan', 'Afghanistan.png'),
(3, 'Aland Islands', 'Aland Islands.png'),
(4, 'Albania', 'Albania.png'),
(5, 'Alderney', 'Alderney.png'),
(6, 'Algeria', 'Algeria.png'),
(7, 'American Samoa', 'American Samoa.png'),
(8, 'Andorra', 'Andorra.png'),
(9, 'Angola', 'Angola.png'),
(10, 'Anguilla.png', 'Anguilla.png'),
(11, 'Antarctica', 'Antarctica.png'),
(12, 'Antigua & Barbuda', 'Antigua & Barbuda.png'),
(13, 'Argentina', 'Argentina.png'),
(14, 'Armenia', 'Armenia.png'),
(15, 'Aruba', 'Aruba.png'),
(16, 'Australia', 'Australia.png'),
(17, 'Austria', 'Austria.png'),
(18, 'Azerbaijan', 'Azerbaijan.png'),
(19, 'Azores', 'Azores.png'),
(20, 'Bahamas', 'Bahamas.png'),
(21, 'Bahrain', 'Bahrain.png'),
(22, 'Bangladesh', 'Bangladesh.png'),
(23, 'Barbados', 'Barbados.png'),
(24, 'Belarus', 'Belarus.png'),
(25, 'Belgium', 'Belgium.png'),
(26, 'Belize', 'Belize.png'),
(27, 'Benin', 'Benin.png'),
(28, 'Bermuda', 'Bermuda.png'),
(29, 'Bhutan', 'Bhutan.png'),
(30, 'Bolivia', 'Bolivia.png'),
(31, 'Bosnia and Herzegovina', 'Bosnia and Herzegovina.png'),
(32, 'Botswana', 'Botswana.png'),
(33, 'Brazil', 'Brazil.png'),
(34, 'Brunei', 'Brunei.png'),
(35, 'Bulgaria', 'Bulgaria.png'),
(36, 'Burkina Faso', 'Burkina Faso.png'),
(37, 'Burundi', 'Burundi.png'),
(38, 'Cambodia', 'Cambodia.png'),
(39, 'Cameroon', 'Cameroon.png'),
(40, 'Canada', 'Canada.png'),
(41, 'Canary Islands', 'Canary Islands.png'),
(42, 'Cape Verde', 'Cape Verde.png'),
(43, 'Cayman Islands', 'Cayman Islands.png'),
(44, 'Central African Republic', 'Central African Republic.png'),
(45, 'Chad', 'Chad.png'),
(46, 'Chile', 'Chile.png'),
(47, 'China', 'China.png'),
(48, 'Christmas Island', 'Christmas Island.png'),
(49, 'Cocos Islands', 'Cocos Islands.png'),
(50, 'Colombia', 'Colombia.png'),
(51, 'Commonwealth', 'Commonwealth.png'),
(52, 'Comoros', 'Comoros.png'),
(53, 'Congo-Brazzaville', 'Congo-Brazzaville.png'),
(54, 'Congo-Kinshasa', 'Congo-Kinshasa.png'),
(55, 'Cook Islands', 'Cook Islands.png'),
(56, 'Costa Rica', 'Costa Rica.png'),
(57, 'Croatia', 'Croatia.png'),
(58, 'Cuba', 'Cuba.png'),
(59, 'Cyprus', 'Cyprus.png'),
(60, 'Czech Republic', 'Czech Republic.png'),
(61, 'Denmark', 'Denmark.png'),
(62, 'Djibouti', 'Djibouti.png'),
(63, 'Dominica', 'Dominica.png'),
(64, 'Dominican Rep', 'Dominican Rep.png'),
(65, 'East Timor', 'East Timor.png'),
(66, 'Ecuador', 'Ecuador.png'),
(67, 'Egypt', 'Egypt.png'),
(68, 'El Salvador', 'El Salvador.png'),
(69, 'England', 'England.png'),
(70, 'Equatorial Guinea', 'Equatorial Guinea.png'),
(71, 'Eritrea', 'Eritrea.png'),
(72, 'Estonia', 'Estonia.png'),
(73, 'Ethiopia', 'Ethiopia.png'),
(74, 'European Union', 'European Union.png'),
(75, 'Falkland Islands', 'Falkland Islands.png'),
(76, 'Faroe Islands', 'Faroe Islands.png'),
(77, 'Fiji', 'Fiji.png'),
(78, 'Finland', 'Finland.png'),
(79, 'France', 'France.png'),
(80, 'French Polynesia', 'French Polynesia.png'),
(81, 'Gabon', 'Gabon.png'),
(82, 'Gambia', 'Gambia.png'),
(83, 'Georgia', 'Georgia.png'),
(84, 'Germany', 'Germany.png'),
(85, 'Ghana', 'Ghana.png'),
(86, 'Gibraltar', 'Gibraltar.png'),
(87, 'Greece', 'Greece.png'),
(88, 'Greenland', 'Greenland.png'),
(89, 'Grenada', 'Grenada.png'),
(90, 'Guam', 'Guam.png'),
(91, 'Guatemala', 'Guatemala.png'),
(92, 'Guernsey', 'Guernsey.png'),
(93, 'Guinea-Bissau', 'Guinea-Bissau.png'),
(94, 'Guinea', 'Guinea.png'),
(95, 'Guyana', 'Guyana.png'),
(96, 'Haiti', 'Haiti.png'),
(97, 'Honduras', 'Honduras.png'),
(98, 'Hong Kong', 'Hong Kong.png'),
(99, 'Hungary', 'Hungary.png'),
(100, 'IAEA', 'IAEA.png'),
(101, 'ICAO', 'ICAO.png'),
(102, 'ICCT', 'ICCT.png'),
(103, 'Iceland', 'Iceland.png'),
(104, 'Ichkeria', 'Ichkeria.png'),
(105, 'ILO', 'ILO.png'),
(106, 'IMO', 'IMO.png'),
(107, 'India', 'India.png'),
(108, 'Indonesia', 'Indonesia.png'),
(109, 'INSTRAW', 'INSTRAW.png'),
(110, 'Iran', 'Iran.png'),
(111, 'Iraq', 'Iraq.png'),
(112, 'Ireland', 'Ireland.png'),
(113, 'Isle of Man', 'Isle of Man.png'),
(114, 'Israel', 'Israel.png'),
(115, 'Italy', 'Italy.png'),
(116, 'ITU', 'ITU.png'),
(117, 'Ivory Coast', 'Ivory Coast.png'),
(118, 'Jamaica', 'Jamaica.png'),
(119, 'Japan', 'Japan.png'),
(120, 'Jersey', 'Jersey.png'),
(121, 'Jordan', 'Jordan.png'),
(122, 'Kazakhstan', 'Kazakhstan.png'),
(123, 'Kenya', 'Kenya.png'),
(124, 'Kiribati', 'Kiribati.png'),
(125, 'Kosovo', 'Kosovo.png'),
(126, 'Kuwait', 'Kuwait.png'),
(127, 'Kyrgyzstan', 'Kyrgyzstan.png'),
(128, 'Laos', 'Laos.png'),
(129, 'Latvia', 'Latvia.png'),
(130, 'League Arab States', 'League Arab States.png'),
(131, 'Lesotho', 'Lesotho.png'),
(132, 'Liberia', 'Liberia.png'),
(133, 'Libya', 'Libya.png'),
(134, 'Liechtenstein', 'Liechtenstein.png'),
(135, 'Lithuania', 'Lithuania.png'),
(136, 'Luxembourg', 'Luxembourg.png'),
(137, 'Macau', 'Macau.png'),
(138, 'Macedonia', 'Macedonia.png'),
(139, 'Madagascar', 'Madagascar.png'),
(140, 'Madeira', 'Madeira.png'),
(141, 'Malawi', 'Malawi.png'),
(142, 'Malaysia', 'Malaysia.png'),
(143, 'Maldives', 'Maldives.png'),
(144, 'Mali', 'Mali.png'),
(145, 'Malta', 'Malta.png'),
(146, 'Marshall Islands', 'Marshall Islands.png'),
(147, 'Mauritania', 'Mauritania.png'),
(148, 'Mauritius', 'Mauritius.png'),
(149, 'Mexico', 'Mexico.png'),
(150, 'Micronesia', 'Micronesia.png'),
(151, 'Moldova', 'Moldova.png'),
(152, 'Monaco', 'Monaco.png'),
(153, 'Mongolia', 'Mongolia.png'),
(154, 'Montenegro', 'Montenegro.png'),
(155, 'Morocco', 'Morocco.png'),
(156, 'Mozambique', 'Mozambique.png'),
(157, 'Myanmar', 'Myanmar.png'),
(158, 'Namibia', 'Namibia.png'),
(159, 'NATO', 'NATO.png'),
(160, 'Nauru', 'Nauru.png'),
(161, 'Nepal', 'Nepal.png'),
(162, 'Netherlands', 'Netherlands.png'),
(163, 'New Zealand', 'New Zealand.png'),
(164, 'Nicaragua', 'Nicaragua.png'),
(165, 'Niger', 'Niger.png'),
(166, 'Nigeria', 'Nigeria.png'),
(167, 'Niue', 'Niue.png'),
(168, 'Norfolk Island', 'Norfolk Island.png'),
(169, 'North Korea', 'North Korea.png'),
(170, 'Northern Ireland', 'Northern Ireland.png'),
(171, 'Norway', 'Norway.png'),
(172, 'Oman', 'Oman.png'),
(173, 'Org. of African Unity', 'Org. of African Unity.png'),
(174, 'Pakistan', 'Pakistan.png'),
(175, 'Palau', 'Palau.png'),
(176, 'Palestinian Territories', 'Palestinian territories.png'),
(177, 'Panama', 'Panama.png'),
(178, 'Papua New Guinea', 'Papua New Guinea.png'),
(179, 'Paraguay', 'Paraguay.png'),
(180, 'Paraguay', 'Peru.png'),
(181, 'Philippines', 'Philippines.png'),
(182, 'Poland', 'Poland.png'),
(183, 'Portugal', 'Portugal.png'),
(184, 'Puerto Rico', 'Puerto Rico.png'),
(185, 'Qatar', 'Qatar.png'),
(186, 'Romania', 'Romania.png'),
(187, 'Russia', 'Russia.png'),
(188, 'Rwanda', 'Rwanda.png'),
(189, 'San Marino', 'San Marino.png'),
(190, 'Sao Tome and Principe', 'Sao Tome and Principe.png'),
(191, 'Saudi Arabia', 'Saudi Arabia.png'),
(192, 'Scotland', 'Scotland.png'),
(193, 'Senegal', 'Senegal.png'),
(194, 'Serbia', 'Serbia.png'),
(195, 'Seychelles', 'Seychelles.png'),
(196, 'Sierra Leone', 'Sierra Leone.png'),
(197, 'Singapore', 'Singapore.png'),
(198, 'Slovakia', 'Slovakia.png'),
(199, 'Slovenia', 'Slovenia.png'),
(200, 'Solomon Islands', 'Solomon Islands.png'),
(201, 'Somalia', 'Somalia.png'),
(202, 'South Africa', 'South Africa.png'),
(203, 'South Korea', 'South Korea.png'),
(204, 'South Pacific Commission', 'South Pacific Commission.png'),
(205, 'Spain', 'Spain.png'),
(206, 'Sri Lanka', 'Sri Lanka.png'),
(207, 'St. Christopher-Nevis', 'St. Christopher-Nevis.png'),
(208, 'St. Helena', 'St. Helena.png'),
(209, 'St. Lucia', 'St. Lucia.png'),
(210, 'St. Vincent', 'St. Vincent.png'),
(211, 'Sudan', 'Sudan.png'),
(212, 'Suriname', 'Suriname.png'),
(213, 'Swaziland', 'Swaziland.png'),
(214, 'Sweden', 'Sweden.png'),
(215, 'Switzerland', 'Switzerland.png'),
(216, 'Syria', 'Syria.png'),
(217, 'Taiwan', 'Taiwan.png'),
(218, 'Tajikistan', 'Tajikistan.png'),
(219, 'Tanzania', 'Tanzania.png'),
(220, 'Thailand', 'Thailand.png'),
(221, 'The Gambia', 'The Gambia.png'),
(222, 'Togo', 'Togo.png'),
(223, 'Tonga', 'Tonga.png'),
(224, 'Trinidad & Tobago', 'Trinidad & Tobago.png'),
(225, 'Tunisia', 'Tunisia.png'),
(226, 'Turkey', 'Turkey.png'),
(227, 'Turkmenistan', 'Turkmenistan.png'),
(228, 'Turks & Caicos', 'Turks & Caicos.png'),
(229, 'Tuvalu', 'Tuvalu.png'),
(230, 'Uganda', 'Uganda.png'),
(231, 'Ukraine', 'Ukraine.png'),
(232, 'UNESCO', 'UNESCO.png'),
(233, 'UNHCR', 'UNHCR.png'),
(234, 'UNICEF', 'UNICEF.png'),
(235, 'United Arab Emirates', 'United Arab Emirates.png'),
(236, 'United Kingdom', 'United Kingdom.png'),
(237, 'United Nations', 'United Nations.png'),
(238, 'United States', 'United States.png'),
(239, 'UNPA', 'UNPA.png'),
(240, 'UNV', 'UNV.png'),
(241, 'UPU', 'UPU.png'),
(242, 'Uruguay', 'Uruguay.png'),
(243, 'Uzbekistan', 'Uzbekistan.png'),
(244, 'Vanuatu', 'Vanuatu.png'),
(245, 'Vatican City', 'Vatican City.png'),
(246, 'Venezuela', 'Venezuela.png'),
(247, 'Vietnam', 'Vietnam.png'),
(248, 'Virgin Islands', 'Virgin Islands.png'),
(249, 'Western Sahara', 'Western Sahara.png'),
(250, 'Western Samoa', 'Western Samoa.png'),
(251, 'WHO', 'WHO.png'),
(252, 'World Bank Flag', 'World Bank Flag.png'),
(253, 'Yemen', 'Yemen.png'),
(254, 'Yugoslavia', 'Yugoslavia.png'),
(255, 'Zambia', 'Zambia.png'),
(256, 'Zimbabwe', 'Zimbabwe.png')";

$INSERT[] = "INSERT INTO `stats` (`id`, `regusers`, `unconusers`, `torrents`, `seeders`, `leechers`, `torrentstoday`, `donors`, `unconnectables`, `forumtopics`, `forumposts`, `numactive`) VALUES (1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1)";

$INSERT[] = "INSERT INTO stylesheets (id, uri, name) VALUES
(1, 'default', '(default)'),
(2, 'pastel', 'Pastel'),
(3, 'dark', 'Dark'),
(4, 'light', 'Light')";

?>